import type { Product } from "../../types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Cyber Quest 2077",
    slug: "cyber-quest-2077",
    description: "An open-world sci-fi RPG set in a futuristic city.",
    price: 59.99,
    imageUrl: "https://via.placeholder.com/300x400?text=Cyber+Quest+2077",
    category: "RPG",
    platform: "PC",
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    title: "Pixel Racers",
    slug: "pixel-racers",
    description: "A fast-paced arcade racing game with retro visuals.",
    price: 24.99,
    imageUrl: "https://via.placeholder.com/300x400?text=Pixel+Racers",
    category: "Racing",
    platform: "PC",
    inStock: true,
    featured: false,
  },
  {
    id: "3",
    title: "Kingdoms of Ash",
    slug: "kingdoms-of-ash",
    description: "A dark fantasy strategy game with deep worldbuilding.",
    price: 49.99,
    imageUrl: "https://via.placeholder.com/300x400?text=Kingdoms+of+Ash",
    category: "Strategy",
    platform: "PC",
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    title: "Galaxy Strikers",
    slug: "galaxy-strikers",
    description: "A multiplayer space shooter with team-based battles.",
    price: 39.99,
    imageUrl: "https://via.placeholder.com/300x400?text=Galaxy+Strikers",
    category: "Shooter",
    platform: "PC",
    inStock: false,
    featured: false,
  },
];